<?php
return [
    'Permissions' => ['role-all' , 'role-view' , 'role-create' , 'role-update' , 'role-delete' ],
    'Members' => ['member-all' , 'member-view' , 'member-create' , 'member-update' , 'member-delete' ],
    'Settings' => ['setting-all' , 'setting-view' , 'setting-create' , 'setting-update' , 'setting-delete' ],
    'SettingsPrivacy' => ['SettingsPrivacy-all' , 'SettingsPrivacy-view' , 'SettingsPrivacy-create' , 'SettingsPrivacy-update' , 'SettingsPrivacy-delete' ],
    'Categories' => ['categories-all' , 'categories-view' , 'categories-create' , 'categories-update' , 'categories-delete' ],
    'Ads' => ['ads-all' , 'ads-view' , 'ads-create' , 'ads-update' , 'ads-delete' ],
    'Products' => ['product-all' , 'product-view' , 'product-create' , 'product-update' , 'product-delete' ],
    'Customers' => ['customer-all' , 'customer-view' , 'customer-create' , 'customer-update' , 'customer-delete' ],
    'Orders' => ['order-all' , 'order-view' , 'order-create' , 'order-update' , 'order-delete' ],
    'Archives' => ['archives-all' , 'archives-view' , 'archives-create' , 'archives-update' , 'archives-delete' ],
    'Contacts' => ['contact-all' , 'contact-view' , 'contact-create' , 'contact-update' , 'contact-delete' ],
    'Product Lists' => ['productList-all' , 'productList-view' , 'productList-create' , 'productList-update' , 'productList-delete' ],
    'Payment Methods' => ['paymentMethod-all' , 'paymentMethod-view' , 'paymentMethod-create' , 'paymentMethod-update' , 'paymentMethod-delete' ],
    'Delivery Methods' => ['deliveryMethods-all' , 'deliveryMethods-view' , 'deliveryMethods-create' , 'deliveryMethods-update' , 'deliveryMethods-delete' ],
    'Reports' => ['report-all' , 'report-view' , 'report-create' , 'report-update' , 'report-delete' ],
    'Notifications' => ['notification-all' , 'notification-view' , 'notification-create' , 'notification-update' , 'notification-delete' ],
    'Discount Codes' => ['discountCodes-all' , 'discountCodes-view' , 'discountCodes-create' , 'discountCodes-update' , 'discountCodes-delete' ],
    'Worktime' => ['workTime-all' , 'workTime-view' , 'workTime-create' , 'workTime-update' , 'workTime-delete' ],
    'Delivery Hours' => ['deliveryHour-all' , 'deliveryHour-view' , 'deliveryHour-create' , 'deliveryHour-update' , 'deliveryHour-delete' ],
    'Regions' => ['region-all' , 'region-view' , 'region-create' , 'region-update' , 'region-delete' ],
//    'Country' => ['region-all' , 'region-view' , 'region-create' , 'region-update' , 'region-delete' ],
];
?>
